from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
import sys
from SpotifyTracker import APImanager

manager = APImanager()

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(758, 589)
        palette = QPalette()
        brush = QBrush(QColor(255, 255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Active, QPalette.Light, brush)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        brush1 = QBrush(QColor(255, 0, 0, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.BrightText, brush1)
        brush2 = QBrush(QColor(85, 255, 127, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush2)
        brush3 = QBrush(QColor(76, 76, 76, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Window, brush3)
        brush4 = QBrush(QColor(85, 170, 255, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.AlternateBase, brush4)
        brush5 = QBrush(QColor(85, 255, 255, 128))
        brush5.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush5)
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Light, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette.setBrush(QPalette.Inactive, QPalette.BrightText, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush3)
        palette.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush5)
        brush6 = QBrush(QColor(120, 120, 120, 255))
        brush6.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush6)
        palette.setBrush(QPalette.Disabled, QPalette.Light, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush6)
        palette.setBrush(QPalette.Disabled, QPalette.BrightText, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush4)
        palette.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush5)
        MainWindow.setPalette(palette)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.listTrackHistory = QListView(self.centralwidget)
        self.listTrackHistory.setObjectName(u"listTrackHistory")
        self.listTrackHistory.setGeometry(QRect(420, 10, 331, 571))
        self.verticalLayoutWidget = QWidget(self.centralwidget)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(120, 286, 55, 61))
        self.verticalLayout = QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.label5 = QLabel(self.verticalLayoutWidget)
        self.label5.setObjectName(u"label5")
        palette1 = QPalette()
        brush7 = QBrush(QColor(180, 180, 180, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush7)
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush7)
        palette1.setBrush(QPalette.Disabled, QPalette.WindowText, brush6)
        self.label5.setPalette(palette1)
        font = QFont()
        font.setPointSize(14)
        self.label5.setFont(font)

        self.verticalLayout.addWidget(self.label5)

        self.label6 = QLabel(self.verticalLayoutWidget)
        self.label6.setObjectName(u"label6")
        palette2 = QPalette()
        palette2.setBrush(QPalette.Active, QPalette.WindowText, brush7)
        palette2.setBrush(QPalette.Inactive, QPalette.WindowText, brush7)
        palette2.setBrush(QPalette.Disabled, QPalette.WindowText, brush6)
        self.label6.setPalette(palette2)
        self.label6.setFont(font)

        self.verticalLayout.addWidget(self.label6)

        self.line = QFrame(self.centralwidget)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(10, 346, 401, 20))
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.verticalLayoutWidget_2 = QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setObjectName(u"verticalLayoutWidget_2")
        self.verticalLayoutWidget_2.setGeometry(QRect(180, 286, 241, 61))
        self.verticalLayout_2 = QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.labelCurrentArtist = QLabel(self.verticalLayoutWidget_2)
        self.labelCurrentArtist.setObjectName(u"labelCurrentArtist")
        font1 = QFont()
        font1.setPointSize(14)
        font1.setItalic(True)
        self.labelCurrentArtist.setFont(font1)

        self.verticalLayout_2.addWidget(self.labelCurrentArtist)

        self.labelCurrentTrack = QLabel(self.verticalLayoutWidget_2)
        self.labelCurrentTrack.setObjectName(u"labelCurrentTrack")
        self.labelCurrentTrack.setFont(font1)

        self.verticalLayout_2.addWidget(self.labelCurrentTrack)

        self.line_3 = QFrame(self.centralwidget)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(10, 426, 401, 20))
        self.line_3.setFrameShape(QFrame.HLine)
        self.line_3.setFrameShadow(QFrame.Sunken)
        self.label2 = QLabel(self.centralwidget)
        self.label2.setObjectName(u"label2")
        self.label2.setGeometry(QRect(10, 380, 91, 31))
        palette3 = QPalette()
        palette3.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette3.setBrush(QPalette.Active, QPalette.Text, brush2)
        brush8 = QBrush(QColor(85, 255, 127, 128))
        brush8.setStyle(Qt.NoBrush)
        palette3.setBrush(QPalette.Active, QPalette.PlaceholderText, brush8)
        palette3.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette3.setBrush(QPalette.Inactive, QPalette.Text, brush2)
        brush9 = QBrush(QColor(85, 255, 127, 128))
        brush9.setStyle(Qt.NoBrush)
        palette3.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush9)
        palette3.setBrush(QPalette.Disabled, QPalette.WindowText, brush6)
        palette3.setBrush(QPalette.Disabled, QPalette.Text, brush6)
        brush10 = QBrush(QColor(85, 255, 127, 128))
        brush10.setStyle(Qt.NoBrush)
        palette3.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush10)
        self.label2.setPalette(palette3)
        font2 = QFont()
        font2.setPointSize(16)
        font2.setBold(True)
        font2.setWeight(75)
        self.label2.setFont(font2)
        self.label2.setAutoFillBackground(False)
        self.verticalLayoutWidget_3 = QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setObjectName(u"verticalLayoutWidget_3")
        self.verticalLayoutWidget_3.setGeometry(QRect(180, 366, 241, 61))
        self.verticalLayout_18 = QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName(u"verticalLayout_18")
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.labelPreviousArtist = QLabel(self.verticalLayoutWidget_3)
        self.labelPreviousArtist.setObjectName(u"labelPreviousArtist")
        self.labelPreviousArtist.setFont(font1)

        self.verticalLayout_18.addWidget(self.labelPreviousArtist)

        self.labelPreviousTrack = QLabel(self.verticalLayoutWidget_3)
        self.labelPreviousTrack.setObjectName(u"labelPreviousTrack")
        self.labelPreviousTrack.setFont(font1)

        self.verticalLayout_18.addWidget(self.labelPreviousTrack)

        self.verticalLayoutWidget_4 = QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setObjectName(u"verticalLayoutWidget_4")
        self.verticalLayoutWidget_4.setGeometry(QRect(120, 366, 55, 61))
        self.verticalLayout_19 = QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_19.setSpacing(2)
        self.verticalLayout_19.setObjectName(u"verticalLayout_19")
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.label_36 = QLabel(self.verticalLayoutWidget_4)
        self.label_36.setObjectName(u"label_36")
        palette4 = QPalette()
        palette4.setBrush(QPalette.Active, QPalette.WindowText, brush7)
        palette4.setBrush(QPalette.Inactive, QPalette.WindowText, brush7)
        palette4.setBrush(QPalette.Disabled, QPalette.WindowText, brush6)
        self.label_36.setPalette(palette4)
        self.label_36.setFont(font)

        self.verticalLayout_19.addWidget(self.label_36)

        self.label_35 = QLabel(self.verticalLayoutWidget_4)
        self.label_35.setObjectName(u"label_35")
        palette5 = QPalette()
        palette5.setBrush(QPalette.Active, QPalette.WindowText, brush7)
        palette5.setBrush(QPalette.Inactive, QPalette.WindowText, brush7)
        palette5.setBrush(QPalette.Disabled, QPalette.WindowText, brush6)
        self.label_35.setPalette(palette5)
        self.label_35.setFont(font)

        self.verticalLayout_19.addWidget(self.label_35)

        self.line_5 = QFrame(self.centralwidget)
        self.line_5.setObjectName(u"line_5")
        self.line_5.setGeometry(QRect(10, 506, 401, 20))
        self.line_5.setFrameShape(QFrame.HLine)
        self.line_5.setFrameShadow(QFrame.Sunken)
        self.label3 = QLabel(self.centralwidget)
        self.label3.setObjectName(u"label3")
        self.label3.setGeometry(QRect(10, 460, 181, 31))
        palette6 = QPalette()
        palette6.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette6.setBrush(QPalette.Active, QPalette.Text, brush2)
        brush11 = QBrush(QColor(85, 255, 127, 128))
        brush11.setStyle(Qt.NoBrush)
        palette6.setBrush(QPalette.Active, QPalette.PlaceholderText, brush11)
        palette6.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette6.setBrush(QPalette.Inactive, QPalette.Text, brush2)
        brush12 = QBrush(QColor(85, 255, 127, 128))
        brush12.setStyle(Qt.NoBrush)
        palette6.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush12)
        palette6.setBrush(QPalette.Disabled, QPalette.WindowText, brush6)
        palette6.setBrush(QPalette.Disabled, QPalette.Text, brush6)
        brush13 = QBrush(QColor(85, 255, 127, 128))
        brush13.setStyle(Qt.NoBrush)
        palette6.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush13)
        self.label3.setPalette(palette6)
        self.label3.setFont(font2)
        self.label3.setAutoFillBackground(False)
        self.label4 = QLabel(self.centralwidget)
        self.label4.setObjectName(u"label4")
        self.label4.setGeometry(QRect(10, 550, 79, 21))
        palette7 = QPalette()
        palette7.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette7.setBrush(QPalette.Active, QPalette.Text, brush2)
        brush14 = QBrush(QColor(85, 255, 127, 128))
        brush14.setStyle(Qt.NoBrush)
        palette7.setBrush(QPalette.Active, QPalette.PlaceholderText, brush14)
        palette7.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette7.setBrush(QPalette.Inactive, QPalette.Text, brush2)
        brush15 = QBrush(QColor(85, 255, 127, 128))
        brush15.setStyle(Qt.NoBrush)
        palette7.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush15)
        palette7.setBrush(QPalette.Disabled, QPalette.WindowText, brush6)
        palette7.setBrush(QPalette.Disabled, QPalette.Text, brush6)
        brush16 = QBrush(QColor(85, 255, 127, 128))
        brush16.setStyle(Qt.NoBrush)
        palette7.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush16)
        self.label4.setPalette(palette7)
        self.label4.setFont(font2)
        self.label4.setAutoFillBackground(False)
        self.labelTime = QLabel(self.centralwidget)
        self.labelTime.setObjectName(u"labelTime")
        self.labelTime.setGeometry(QRect(120, 546, 81, 29))
        font3 = QFont()
        font3.setPointSize(16)
        font3.setItalic(True)
        self.labelTime.setFont(font3)
        self.progressBar = QProgressBar(self.centralwidget)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setGeometry(QRect(200, 464, 211, 23))
        self.progressBar.setValue(24)
        self.progressBar.setTextVisible(False)
        self.label1 = QLabel(self.centralwidget)
        self.label1.setObjectName(u"label1")
        self.label1.setGeometry(QRect(10, 300, 79, 31))
        palette8 = QPalette()
        palette8.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette8.setBrush(QPalette.Active, QPalette.Text, brush2)
        brush17 = QBrush(QColor(85, 255, 127, 128))
        brush17.setStyle(Qt.NoBrush)
        palette8.setBrush(QPalette.Active, QPalette.PlaceholderText, brush17)
        palette8.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette8.setBrush(QPalette.Inactive, QPalette.Text, brush2)
        brush18 = QBrush(QColor(85, 255, 127, 128))
        brush18.setStyle(Qt.NoBrush)
        palette8.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush18)
        palette8.setBrush(QPalette.Disabled, QPalette.WindowText, brush6)
        palette8.setBrush(QPalette.Disabled, QPalette.Text, brush6)
        brush19 = QBrush(QColor(85, 255, 127, 128))
        brush19.setStyle(Qt.NoBrush)
        palette8.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush19)
        self.label1.setPalette(palette8)
        self.label1.setFont(font2)
        self.label1.setAutoFillBackground(False)
        self.horizontalLayoutWidget = QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setObjectName(u"horizontalLayoutWidget")
        self.horizontalLayoutWidget.setGeometry(QRect(20, 10, 381, 261))
        self.horizontalLayout = QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setSpacing(12)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.buttonPreviousTrack = QPushButton(self.horizontalLayoutWidget)
        self.buttonPreviousTrack.setObjectName(u"buttonPreviousTrack")
        palette9 = QPalette()
        palette9.setBrush(QPalette.Active, QPalette.Button, brush3)
        palette9.setBrush(QPalette.Active, QPalette.Base, brush3)
        palette9.setBrush(QPalette.Active, QPalette.Window, brush3)
        palette9.setBrush(QPalette.Inactive, QPalette.Button, brush3)
        palette9.setBrush(QPalette.Inactive, QPalette.Base, brush3)
        palette9.setBrush(QPalette.Inactive, QPalette.Window, brush3)
        palette9.setBrush(QPalette.Disabled, QPalette.Button, brush3)
        palette9.setBrush(QPalette.Disabled, QPalette.Base, brush3)
        palette9.setBrush(QPalette.Disabled, QPalette.Window, brush3)
        self.buttonPreviousTrack.setPalette(palette9)
        self.buttonPreviousTrack.setAutoFillBackground(False)
        self.buttonPreviousTrack.setStyleSheet(u"background-color: rgb(76, 76, 76);\n"
            "border: none;")
        icon = QIcon()
        icon.addFile(u"res/previous_icon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.buttonPreviousTrack.setIcon(icon)
        self.buttonPreviousTrack.setIconSize(QSize(55, 55))

        self.horizontalLayout.addWidget(self.buttonPreviousTrack)

        self.verticalLayout_3 = QVBoxLayout()
        self.verticalLayout_3.setSpacing(12)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.graphicCoverArt = QGraphicsView(self.horizontalLayoutWidget)
        self.graphicCoverArt.setObjectName(u"graphicCoverArt")

        self.verticalLayout_3.addWidget(self.graphicCoverArt)

        self.buttonPlayPause = QPushButton(self.horizontalLayoutWidget)
        self.buttonPlayPause.setObjectName(u"buttonPlayPause")
        palette10 = QPalette()
        palette10.setBrush(QPalette.Active, QPalette.Button, brush3)
        palette10.setBrush(QPalette.Active, QPalette.Base, brush3)
        palette10.setBrush(QPalette.Active, QPalette.Window, brush3)
        palette10.setBrush(QPalette.Inactive, QPalette.Button, brush3)
        palette10.setBrush(QPalette.Inactive, QPalette.Base, brush3)
        palette10.setBrush(QPalette.Inactive, QPalette.Window, brush3)
        palette10.setBrush(QPalette.Disabled, QPalette.Button, brush3)
        palette10.setBrush(QPalette.Disabled, QPalette.Base, brush3)
        palette10.setBrush(QPalette.Disabled, QPalette.Window, brush3)
        self.buttonPlayPause.setPalette(palette10)
        self.buttonPlayPause.setAutoFillBackground(False)
        self.buttonPlayPause.setStyleSheet(u"background-color: rgb(76, 76, 76);\n"
            "border: none;")
        icon1 = QIcon()
        icon1.addFile(u"res/play_pause_icon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.buttonPlayPause.setIcon(icon1)
        self.buttonPlayPause.setIconSize(QSize(55, 55))

        self.verticalLayout_3.addWidget(self.buttonPlayPause)


        self.horizontalLayout.addLayout(self.verticalLayout_3)

        self.buttonNextTrack = QPushButton(self.horizontalLayoutWidget)
        self.buttonNextTrack.setObjectName(u"buttonNextTrack")
        palette11 = QPalette()
        palette11.setBrush(QPalette.Active, QPalette.Button, brush3)
        palette11.setBrush(QPalette.Active, QPalette.Base, brush3)
        palette11.setBrush(QPalette.Active, QPalette.Window, brush3)
        palette11.setBrush(QPalette.Inactive, QPalette.Button, brush3)
        palette11.setBrush(QPalette.Inactive, QPalette.Base, brush3)
        palette11.setBrush(QPalette.Inactive, QPalette.Window, brush3)
        palette11.setBrush(QPalette.Disabled, QPalette.Button, brush3)
        palette11.setBrush(QPalette.Disabled, QPalette.Base, brush3)
        palette11.setBrush(QPalette.Disabled, QPalette.Window, brush3)
        self.buttonNextTrack.setPalette(palette11)
        self.buttonNextTrack.setAutoFillBackground(False)
        self.buttonNextTrack.setStyleSheet(u"background-color: rgb(76, 76, 76);\n"
            "border: none;")
        icon2 = QIcon()
        icon2.addFile(u"res/next_icon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.buttonNextTrack.setIcon(icon2)
        self.buttonNextTrack.setIconSize(QSize(55, 55))

        self.horizontalLayout.addWidget(self.buttonNextTrack)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)

        # button handling
        self.buttonPlayPause.clicked.connect(onPlayPauseClick)
        self.buttonPreviousTrack.clicked.connect(onPreviousTrackClick)
        self.buttonNextTrack.clicked.connect(onNextTrackClick)

        # timer
        self.labelTime.setText(datetime.datetime.now().strftime("Time: %H:%M:%S"))
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label5.setText(QCoreApplication.translate("MainWindow", u"Artist:", None))
        self.label6.setText(QCoreApplication.translate("MainWindow", u"Track:", None))
        self.labelCurrentArtist.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.labelCurrentTrack.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.label2.setText(QCoreApplication.translate("MainWindow", u"Previous", None))
        self.labelPreviousArtist.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.labelPreviousTrack.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.label_36.setText(QCoreApplication.translate("MainWindow", u"Artist:", None))
        self.label_35.setText(QCoreApplication.translate("MainWindow", u"Track:", None))
        self.label3.setText(QCoreApplication.translate("MainWindow", u"Song Popularity", None))
        self.label4.setText(QCoreApplication.translate("MainWindow", u"Time", None))
        self.labelTime.setText(QCoreApplication.translate("MainWindow", u"time", None))
        self.label1.setText(QCoreApplication.translate("MainWindow", u"Current", None))
        self.buttonPreviousTrack.setText("")
        self.buttonPlayPause.setText("")
        self.buttonNextTrack.setText("")

def onPlayPauseClick():
    manager.playPause()

def onPreviousTrackClick():
    manager.previousTrack()

def onNextTrackClick():
    manager.nextTrack()

# create pyqt5 window
class MainWindow(QtWidgets.QMainWindow):
    def __init__(self, parent=None):
        super(MainWindow, self).__init__(parent=parent)
        ui = Ui_MainWindow()
        ui.setupUi(self)

# run application
if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    w = MainWindow()
    w.show()
    sys.exit(app.exec_())

