from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
import sys
from SpotifyTracker import APImanager

manager = APImanager()
track = manager.getPlaying()


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(762, 573)
        palette = QPalette()
        brush = QBrush(QColor(255, 255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Active, QPalette.Light, brush)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        brush1 = QBrush(QColor(255, 0, 0, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.BrightText, brush1)
        brush2 = QBrush(QColor(85, 255, 127, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush2)
        brush3 = QBrush(QColor(47, 47, 47, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Window, brush3)
        brush4 = QBrush(QColor(85, 170, 255, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.AlternateBase, brush4)
        brush5 = QBrush(QColor(85, 255, 255, 128))
        brush5.setStyle(Qt.SolidPattern)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush5)
#endif
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Light, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette.setBrush(QPalette.Inactive, QPalette.BrightText, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush3)
        palette.setBrush(QPalette.Inactive, QPalette.AlternateBase, brush4)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush5)
#endif
        brush6 = QBrush(QColor(120, 120, 120, 255))
        brush6.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush6)
        palette.setBrush(QPalette.Disabled, QPalette.Light, brush)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush6)
        palette.setBrush(QPalette.Disabled, QPalette.BrightText, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.AlternateBase, brush4)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush5)
#endif
        MainWindow.setPalette(palette)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.listTrackHistory = QListView(self.centralwidget)
        self.listTrackHistory.setObjectName(u"listTrackHistory")
        self.listTrackHistory.setGeometry(QRect(420, 20, 331, 541))
        self.graphicAlbumArt = QGraphicsView(self.centralwidget)
        self.graphicAlbumArt.setObjectName(u"graphicAlbumArt")
        self.graphicAlbumArt.setGeometry(QRect(110, 20, 200, 200))
        self.verticalLayoutWidget = QWidget(self.centralwidget)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(120, 260, 55, 61))
        self.verticalLayout = QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.label5 = QLabel(self.verticalLayoutWidget)
        self.label5.setObjectName(u"label5")
        font = QFont()
        font.setPointSize(14)
        self.label5.setFont(font)

        self.verticalLayout.addWidget(self.label5)

        self.label6 = QLabel(self.verticalLayoutWidget)
        self.label6.setObjectName(u"label6")
        self.label6.setFont(font)

        self.verticalLayout.addWidget(self.label6)

        self.line = QFrame(self.centralwidget)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(10, 320, 401, 20))
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.verticalLayoutWidget_2 = QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setObjectName(u"verticalLayoutWidget_2")
        self.verticalLayoutWidget_2.setGeometry(QRect(180, 260, 241, 61))
        self.verticalLayout_2 = QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.labelCurrentArtist = QLabel(self.verticalLayoutWidget_2)
        self.labelCurrentArtist.setObjectName(u"labelCurrentArtist")
        self.labelCurrentArtist.setFont(font)

        self.verticalLayout_2.addWidget(self.labelCurrentArtist)

        self.labelCurrentTrack = QLabel(self.verticalLayoutWidget_2)
        self.labelCurrentTrack.setObjectName(u"labelCurrentTrack")
        self.labelCurrentTrack.setFont(font)

        self.verticalLayout_2.addWidget(self.labelCurrentTrack)

        self.line_2 = QFrame(self.centralwidget)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(110, 260, 3, 61))
        self.line_2.setFrameShape(QFrame.VLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.line_3 = QFrame(self.centralwidget)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(10, 400, 401, 20))
        self.line_3.setFrameShape(QFrame.HLine)
        self.line_3.setFrameShadow(QFrame.Sunken)
        self.label2 = QLabel(self.centralwidget)
        self.label2.setObjectName(u"label2")
        self.label2.setGeometry(QRect(10, 354, 91, 31))
        palette1 = QPalette()
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette1.setBrush(QPalette.Active, QPalette.Text, brush2)
        brush7 = QBrush(QColor(85, 255, 127, 128))
        brush7.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Active, QPalette.PlaceholderText, brush7)
#endif
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette1.setBrush(QPalette.Inactive, QPalette.Text, brush2)
        brush8 = QBrush(QColor(85, 255, 127, 128))
        brush8.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush8)
#endif
        palette1.setBrush(QPalette.Disabled, QPalette.WindowText, brush6)
        palette1.setBrush(QPalette.Disabled, QPalette.Text, brush6)
        brush9 = QBrush(QColor(85, 255, 127, 128))
        brush9.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush9)
#endif
        self.label2.setPalette(palette1)
        font1 = QFont()
        font1.setPointSize(16)
        font1.setBold(True)
        font1.setWeight(75)
        self.label2.setFont(font1)
        self.label2.setAutoFillBackground(False)
        self.verticalLayoutWidget_3 = QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setObjectName(u"verticalLayoutWidget_3")
        self.verticalLayoutWidget_3.setGeometry(QRect(180, 340, 241, 61))
        self.verticalLayout_18 = QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName(u"verticalLayout_18")
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.labelPreviousArtist = QLabel(self.verticalLayoutWidget_3)
        self.labelPreviousArtist.setObjectName(u"labelPreviousArtist")
        self.labelPreviousArtist.setFont(font)

        self.verticalLayout_18.addWidget(self.labelPreviousArtist)

        self.labelPreviousTrack = QLabel(self.verticalLayoutWidget_3)
        self.labelPreviousTrack.setObjectName(u"labelPreviousTrack")
        self.labelPreviousTrack.setFont(font)

        self.verticalLayout_18.addWidget(self.labelPreviousTrack)

        self.verticalLayoutWidget_4 = QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setObjectName(u"verticalLayoutWidget_4")
        self.verticalLayoutWidget_4.setGeometry(QRect(120, 340, 55, 61))
        self.verticalLayout_19 = QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_19.setSpacing(2)
        self.verticalLayout_19.setObjectName(u"verticalLayout_19")
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.label_36 = QLabel(self.verticalLayoutWidget_4)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setFont(font)

        self.verticalLayout_19.addWidget(self.label_36)

        self.label_35 = QLabel(self.verticalLayoutWidget_4)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setFont(font)

        self.verticalLayout_19.addWidget(self.label_35)

        self.line_4 = QFrame(self.centralwidget)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(110, 340, 3, 61))
        self.line_4.setFrameShape(QFrame.VLine)
        self.line_4.setFrameShadow(QFrame.Sunken)
        self.line_5 = QFrame(self.centralwidget)
        self.line_5.setObjectName(u"line_5")
        self.line_5.setGeometry(QRect(10, 480, 401, 20))
        self.line_5.setFrameShape(QFrame.HLine)
        self.line_5.setFrameShadow(QFrame.Sunken)
        self.label3 = QLabel(self.centralwidget)
        self.label3.setObjectName(u"label3")
        self.label3.setGeometry(QRect(10, 434, 79, 31))
        palette2 = QPalette()
        palette2.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette2.setBrush(QPalette.Active, QPalette.Text, brush2)
        brush10 = QBrush(QColor(85, 255, 127, 128))
        brush10.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Active, QPalette.PlaceholderText, brush10)
#endif
        palette2.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette2.setBrush(QPalette.Inactive, QPalette.Text, brush2)
        brush11 = QBrush(QColor(85, 255, 127, 128))
        brush11.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush11)
#endif
        palette2.setBrush(QPalette.Disabled, QPalette.WindowText, brush6)
        palette2.setBrush(QPalette.Disabled, QPalette.Text, brush6)
        brush12 = QBrush(QColor(85, 255, 127, 128))
        brush12.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush12)
#endif
        self.label3.setPalette(palette2)
        self.label3.setFont(font1)
        self.label3.setAutoFillBackground(False)
        self.verticalLayoutWidget_5 = QWidget(self.centralwidget)
        self.verticalLayoutWidget_5.setObjectName(u"verticalLayoutWidget_5")
        self.verticalLayoutWidget_5.setGeometry(QRect(180, 420, 241, 61))
        self.verticalLayout_20 = QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_20.setSpacing(0)
        self.verticalLayout_20.setObjectName(u"verticalLayout_20")
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.labelNextArtist = QLabel(self.verticalLayoutWidget_5)
        self.labelNextArtist.setObjectName(u"labelNextArtist")
        self.labelNextArtist.setFont(font)

        self.verticalLayout_20.addWidget(self.labelNextArtist)

        self.labelNextTrack = QLabel(self.verticalLayoutWidget_5)
        self.labelNextTrack.setObjectName(u"labelNextTrack")
        self.labelNextTrack.setFont(font)

        self.verticalLayout_20.addWidget(self.labelNextTrack)

        self.verticalLayoutWidget_6 = QWidget(self.centralwidget)
        self.verticalLayoutWidget_6.setObjectName(u"verticalLayoutWidget_6")
        self.verticalLayoutWidget_6.setGeometry(QRect(120, 420, 55, 61))
        self.verticalLayout_21 = QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_21.setSpacing(2)
        self.verticalLayout_21.setObjectName(u"verticalLayout_21")
        self.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.label_42 = QLabel(self.verticalLayoutWidget_6)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setFont(font)

        self.verticalLayout_21.addWidget(self.label_42)

        self.label_37 = QLabel(self.verticalLayoutWidget_6)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setFont(font)

        self.verticalLayout_21.addWidget(self.label_37)

        self.line_6 = QFrame(self.centralwidget)
        self.line_6.setObjectName(u"line_6")
        self.line_6.setGeometry(QRect(110, 420, 3, 61))
        self.line_6.setFrameShape(QFrame.VLine)
        self.line_6.setFrameShadow(QFrame.Sunken)
        self.label4 = QLabel(self.centralwidget)
        self.label4.setObjectName(u"label4")
        self.label4.setGeometry(QRect(10, 524, 79, 21))
        palette3 = QPalette()
        palette3.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette3.setBrush(QPalette.Active, QPalette.Text, brush2)
        brush13 = QBrush(QColor(85, 255, 127, 128))
        brush13.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.Active, QPalette.PlaceholderText, brush13)
#endif
        palette3.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette3.setBrush(QPalette.Inactive, QPalette.Text, brush2)
        brush14 = QBrush(QColor(85, 255, 127, 128))
        brush14.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush14)
#endif
        palette3.setBrush(QPalette.Disabled, QPalette.WindowText, brush6)
        palette3.setBrush(QPalette.Disabled, QPalette.Text, brush6)
        brush15 = QBrush(QColor(85, 255, 127, 128))
        brush15.setStyle(Qt.NoBrush)
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette3.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush15)
#endif
        self.label4.setPalette(palette3)
        self.label4.setFont(font1)
        self.label4.setAutoFillBackground(False)
        self.line_8 = QFrame(self.centralwidget)
        self.line_8.setObjectName(u"line_8")
        self.line_8.setGeometry(QRect(110, 500, 3, 61))
        self.line_8.setFrameShape(QFrame.VLine)
        self.line_8.setFrameShadow(QFrame.Sunken)
        self.labelTime = QLabel(self.centralwidget)
        self.labelTime.setObjectName(u"labelTime")
        self.labelTime.setGeometry(QRect(120, 520, 81, 29))
        font2 = QFont()
        font2.setPointSize(16)
        self.labelTime.setFont(font2)
        self.label1 = QLabel(self.centralwidget)
        self.label1.setObjectName(u"label1")
        self.label1.setGeometry(QRect(10, 274, 79, 31))
        palette4 = QPalette()
        palette4.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        palette4.setBrush(QPalette.Active, QPalette.Text, brush2)
        palette4.setBrush(QPalette.Inactive, QPalette.WindowText, brush2)
        palette4.setBrush(QPalette.Inactive, QPalette.Text, brush2)
        palette4.setBrush(QPalette.Disabled, QPalette.WindowText, brush6)
        palette4.setBrush(QPalette.Disabled, QPalette.Text, brush6)
        self.label1.setPalette(palette4)
        self.label1.setFont(font1)
        self.label1.setAutoFillBackground(False)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label5.setText(QCoreApplication.translate("MainWindow", u"Artist:", None))
        self.label6.setText(QCoreApplication.translate("MainWindow", u"Track:", None))
        self.labelCurrentArtist.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.labelCurrentTrack.setText(QCoreApplication.translate("MainWindow", track, None))
        self.label2.setText(QCoreApplication.translate("MainWindow", u"Previous", None))
        self.labelPreviousArtist.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.labelPreviousTrack.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.label_36.setText(QCoreApplication.translate("MainWindow", u"Artist:", None))
        self.label_35.setText(QCoreApplication.translate("MainWindow", u"Track:", None))
        self.label3.setText(QCoreApplication.translate("MainWindow", u"Next", None))
        self.labelNextArtist.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.labelNextTrack.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.label_42.setText(QCoreApplication.translate("MainWindow", u"Artist:", None))
        self.label_37.setText(QCoreApplication.translate("MainWindow", u"Track:", None))
        self.label4.setText(QCoreApplication.translate("MainWindow", u"Time", None))
        self.labelTime.setText(QCoreApplication.translate("MainWindow", u"time", None))
        self.label1.setText(QCoreApplication.translate("MainWindow", u"Current", None))
    # retranslateUi



class MainWindow(QtWidgets.QMainWindow):
    def __init__(self, parent=None):
        super(MainWindow, self).__init__(parent=parent)
        ui = Ui_MainWindow()
        ui.setupUi(self)


if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    w = MainWindow()
    w.show()
    sys.exit(app.exec_())

